### PR TITLE
Change moment for date-fns

### PR DESCRIPTION
**Pull request by joecohens**
This should help in speed and bundle size.

### CODE REVIEW

**Comment by rauchg** [comment]
😍 I'll have @leo review though!

**Comment by joecohens** [comment]
😉

**Comment by leo** [comment]
wow, thank you! wanted to do that for some time now 😊

**Comment by joecohens** [comment]
No problem! I had it fresh from doing https://epoch.now.sh/ lol

**Comment by leo** [comment]
Hehe 😊 Released on channels!

**Comment by joecohens** [comment]
Awesome!

**Pull request merged**
