### PR TITLE
Fix titlebar window inset after upgrade to latest electron

### PR DESCRIPTION
**Pull request by joecohens**
/cc @leo update inset title bar style to Electron 2.0

### CODE REVIEW

**Comment by leo** [comment]
Thank you! 💃

**Comment by leo** [comment]
@joecohens Since you've been deep into the codebase by now, do you have any idea why our integration tests are so brittle?

I built them myself a while ago and they worked extremely well since. However, they sometimes randomly fail. And then, if you restart them, they go green again. I haven't managed to fix it yet, so maybe you have an idea?

As you can see on the commit list (the red crosses), it makes releasing take hours.

**Comment by joecohens** [comment]
@leo Yeah I've seeing this behavior happen on some PR's, I'll take a look at it soon.

**Comment by leo** [comment]
@joecohens You're an angel!

**Comment by joecohens** [comment]
😇

**Pull request merged**
