### PR TITLE
Improved Now CLI's installation flow

### PR DESCRIPTION
**Pull request by melvin0008**
Fixes issue #390 

Summary of the changes
1. When the app starts if the cli is not installed the binary is downloaded and stored in a temp directory.
2. When the user verifies, the binary is moved to the destination
3. If the user unchecks the checkbox to disable CLI installation, updateCLI flag in config is set as false.
4. If the user switches on Auto CLI update, we install the app.

screen shot 2017-11-12 at 10 24 29 pm

### CODE REVIEW

**Comment by melvin0008** [comment]
@leo Let me know if I can help in improving this PR. Would love to do so :)

**Comment by leo** [comment]
@melvin0008 Thank you so much for this wonderful PR!

I only had to adjust a few tiny styling- and syntax-related issues and fix the wording in the intro. Now this is ready to be published on the canary channel!

I'm on it... 😊

**Comment by leo** [comment]
[Released!](https://github.com/zeit/now-desktop/releases/tag/3.7.0) - Thank you, again 😊

**Comment by melvin0008** [comment]
Thanks a lot for your guidance on the same. I would love to contribute more often to zeit projects :)

**Comment by leo** [comment]
That would be wonderful! 🎉 

I will also make sure to mention you when announcing this feature.

**Pull request merged**
